### ISSUE TITLE
is this even working?

### ISSUE THREAD

**Issue by daveteu** [sabljakovich/mongoose-execution-time#1]
anyone got this working? 

Installed as per instructions, nothing is shown..

```
        const { logExecutionTime } = require('mongoose-execution-time');
        mongoose.plugin(logExecutionTime);

       mongoose.connection(....
```

**Comment by vimox-shah** [comment]
Facing the issue with nestjs. not working

**Comment by sabljakovich** [comment]
Hello @daveteu & @vimox-shah, sorry to hear you are having issues, please provide more details. Also, I have pushed a working [example project]( https://github.com/sabljakovich/mongoose-execution-time/tree/master/example ).
